name: TributeWaters
favicon: null
layout_spectrum: 0.2272
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#754c0e'
    - '#7498b0'
    - '#d8bf00'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
