name: TributeWaters
favicon: null
layout_spectrum: 0.012339164037257433
typography_spectrum: 0.38699120515957475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25517024588771164
  lightness: 0.6003601802513003
  saturation: 0.3956256629899144
  rhythmicContrast: 0.2334186970256269
purpose: []
